version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - timescale-data:/var/lib/postgresql/data

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    environment:
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD_PASSWORD}
      EMQX_LISTENERS__SSL__DEFAULT__ENABLE: "true"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "18083:18083"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:z
      - redis-data:/data
    restart: unless-stopped

volumes:
  timescale-data:
  redis-data:
