# Porta
port 6379
bind 0.0.0.0

# Autenticação
# requirepass sua_senha_forte_aqui

# Persistência (RDB)
save 900 1
save 300 10
save 60 10000

# Persistência (AOF - Append Only File)
appendonly yes
appendfsync everysec

# Máximo de memória
maxmemory 512mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice
